const _ = require('lodash');

const build = (options) => _.merge({
  id: 'ZCEX7VTF',
  archived: false,
  masterSchemeId: 'ZCEX7VTF',
  coreSchemeId: '5cd15360091b0149d4da595d-69',
  schemeName: 'No Tension Max Value',
  description: 'Scheme for loan amount less than 2L',
  tenure: 6,
  groupTags: ['migrated', 'cust-facing'],
  applicableProcesses: ['takeover-loan', 'fresh-loan', 'part-release', 'renewal', 'loan-enhancement'],
  goldBenchmark: 'agloc',
  interestCalculation: {
    interestRate: 20.28,
    type: 'flat',
    interestType: 'simple',
    compoundingPeriod: null,
  },
  customerLtv: 74,
  enabled: true,
  baseSchemes: [{
    id: '5f90416f84047040c9ef2856',
    archived: false,
    baseSchemeId: '9185Z78B',
    legalName: 'KVB Gold Loan 6M',
    type: 'secure',
    lenderId: '5cd15360091b0149d4da595d',
    goldBenchmark: 'kvb',
    interestCalculation: {
      interestRate: 19.76,
      type: 'flat',
      interestType: 'simple',
      compoundingPeriod: null,
    },
    addons: [{
      id: '5f90416f84047040c9ef2854',
      archived: false,
      type: 'flat',
      description: null,
      cashback: true,
      interestRate: 20.28,
    }],
    charges: [{
      id: '5f90416f84047040c9ef2858',
      archived: false,
      baseSchemeId: '9185Z78B',
      chargeName: 'Penal Charge',
      chargeType: 'penal',
      chargeCalculationType: 'fixed-percentage',
      applicableProcesses: ['release'],
      chargeValue: 2,
      maxValue: null,
      cityId: null,
    }],
    ltv: 70,
  }, {
    id: '5f90416f84047040c9ef285a',
    archived: false,
    baseSchemeId: 'L1A1I7M9',
    legalName: 'Support GL',
    type: 'unsecure',
    lenderId: '5ac601e1f06f2ce544804433',
    goldBenchmark: 'agloc',
    interestCalculation: {
      interestRate: 29.38,
      type: 'flat',
      interestType: 'simple',
      compoundingPeriod: null,
    },
    addons: [],
    maxThresholdLtvPercentage: 74,
    minThresholdLtvPercentage: 0,
  }],
  eligibility: {
    id: '5f90416f84047040c9ef285e',
    archived: false,
    masterSchemeId: 'ZCEX7VTF',
    ticketSizeMinAmount: 20000,
    ticketSizeMaxAmount: 200000,
    cityIds: [1],
  },
  displayConfigs: [{
    id: '5f90416f84047040c9ef2860',
    archived: false,
    masterSchemeId: 'ZCEX7VTF',
    client: null,
    displayType: null,
    displayProperties: {
      ltvText: 'MAX VALUE',
      referenceName: 'Kvb Flat 74 20.28% 6M <2L',
    },
    visible: true,
  }],
  productCategory: 'goldloan',
}, options);

module.exports = { build };
