import getEnv from '@/utils/env';

export default {
  urls: {
    sendOtp: '/api/v2/auth/sendotp',
    setPin: '/api/v1/auth/setPin',
    loginWithPin: '/api/v1/auth/pinLogin',
    recoverPin: '/api/v1/auth/recoverPin',
    otpLogin: '/api/v2/auth/otplogin',
    login: '/api/customerdetails',
    logout: '/api/v1/auth/logout',
    fetchOrder: '/api/v1/orders/renewals',
    viewDocument: '/api/v2/orders/renewals',
    fetchSignMethods: '/signingmethods',
    paymentMethods: '/paymentmethods',
    payment: '/payment',
    getPaymentDetails: '/web/pay/',
    getPaymentDetailsWithAuth: '/api/mpay/',
    getCustomerBankDetails: '/api/v1/customer/accounts',
    resendOtpToCustomer: '/api/v1/customer/accounts/otp',
    releaseOrderAPI: '/api/v1/pb/orders',
    getSlotsDates: '/api/v1/pb/slots',
    updateOrderDetails: '/api/v1/pb/release/slot',
    AddressValidationAPI: '/api/v1/pb/address/validation',
    staticMessageAPI: '/api/v1/pb/staticmessage',
    getQuickLinks: '/api/v1/loans/quick-links',
    getDiscrepancyMessage: '/api/v1/cache/discrepancy/message',
    partPaymentSplitUrl: '/api/v2/support/getpartpaymentsplit',
    paymentMethodsAPI: '/web/getPaymentOptions',
    sendvansms: '/web/virutalaccount/sendvansms',
    getPaymentLink: '/api/v2/getpaymentlink',
    getPaymentDetailsWithAuthV2: '/api/v2/mpay/',
    getPaymentSuccessError: '/payments/',
    getPaymentFinalStatusAPI: '/api/payment/status',
    getPaymentFinalStatusMobileAPI: '/api/mpayment/status',
    getOmsId: '/api/v1/orders/payment',
    partReleaseFeatureFlagAPI: '/api/v1/pb/flags',
    getJewelsListAPI: '/api/v2/pb/jewellist',
    partReleaseValidateAPI: '/api/v1/pb/partrelease/validations',
    getPaymentOptionsAPI: '/api/v1/pb/orders/paymentoptions',
    getPartReleasePaymentsLinkAPI: '/api/v1/pb/orders/paymentlink',
    loanDetailForRequestIdAPI: '/api/payment/loandetails',
    addressUpdateAPI: '/api/v1/pb/address/update',
    customersAPI: '/web/V4/getuserloans',
    getLenderConfiguration: '/web/lenderOptions',
    getLendersUrl: '/api/publicSchemes',
    getGoldReleaseAPI: '/api/release/getavailability',
    createGoldReleaseSlotsAPI: '/api/release/create',
    getGoldReleaseRequestSuccessAPI: '/api/release/getRequest',
    getExcessFundingAPI: '/api/validate/recovery',
    getNewLoan: '/api/v5/repledge/getnewloan',
    replegeLoanDetails: '/api/support/multipleloanrenewalcalculation',
    fetchSignedDoc: '/api/v2/repledge/fetchsignpledgecard',
    getPostOrderIdUrl: '/api/v1/orders/renewals',
    fetchOrderId: '/api/v3/orders/renewals',
    getRenewalSchemes: '/api/v2/support/renewalScheme',
    getRenewalPendingOrders: '/api/v1/orders/active',
    operationAlmetricsAPI: '/api/operationalmetrics',
    loanEnhancementOptions: '/api/v1/repledge/loanEnhancementOptions',
    renewalEligibility: '/api/support/renewalEligibility',
    partReleaseOrderAPI: '/api/v1/pb/orders',
    getPartReleaseStaticMessageAPI: '/api/v1/pb/staticmessage',
    lendingPartnersAPI: '/api/v1/lendingPartners',
    jwtValidateAPI: '/api/v1/auth/jwtvalidate',
    additionalChargesAPI: '/api/v1/loans/charges',
  },
  closedLoansCarouselSettings: {
    dots: false,
    arrows: false,
    infinite: false,
    touchMove: true,
    speed: 500,
    slidesToShow: 3.1,
    slidesToScroll: 1,
    initialSlide: 0,
    responsive: [
      {
        breakpoint: 1030,
        settings: {
          slidesToShow: 2.5,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 1.5,
        },
      },
      {
        breakpoint: 400,
        settings: {
          slidesToShow: 1.4,
        },
      },
      {
        breakpoint: 360,
        settings: {
          slidesToShow: 1.1,
        },
      },
    ],
  },
  releaseDeliveryStatus: {
    PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
    SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
    SLOT_PENDING: 'SLOT_PENDING',
    SLOT_BOOKED: 'SLOT_BOOKED',
    DELIVERY_INITIATED: 'DELIVERY_INITIATED',
    DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',
  },
  apiEndpoints: {
    loginAAAAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_AAA_HOST')}`,
    loansHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_LOAN_HOST')}`,
    payHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_PAY_HOST')}`,
    losHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_RELEASE_HOST')}`,
    omsHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_OMS_HOST')}`,
    cisHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_CIS_HOST')}`,
    ReferralHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_REFERRAL_HOST')}`,
    lendingHostAPI: `${getEnv('VUE_APP_API_GATEWAY_URI')}/${getEnv('VUE_APP_LENDING_HOST')}`,
  },
};
