import Vue from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faUserCircle,
  faSearchPlus,
  faRupeeSign,
  faPeopleCarry,
  faListOl,
  faMapMarkedAlt,
  faBars,
  faPlusCircle,
  faAngleDoubleLeft,
  faChevronRight,
  faTimes,
  faArrowsAltV,
  faArrowRight,
  faUsers,
  faCoins,
  faCheckDouble,
  faBan,
  faBalanceScale,
  faBook,
  faAngleDown,
  faList,
  faDotCircle,
  faSignOutAlt,
  faStarOfLife,
  faEllipsisV,
} from '@fortawesome/free-solid-svg-icons';
import {
  faClock,
  faCalendarAlt,
  faBell,
  faStar,
  faEdit,
  faTrashAlt,
  faTimesCircle,
  faChartBar,
} from '@fortawesome/free-regular-svg-icons';
import { faHubspot } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

// Font awesome register
library.add(
  faUserCircle,
  faClock,
  faSearchPlus,
  faCalendarAlt,
  faRupeeSign,
  faBell,
  faPeopleCarry,
  faListOl,
  faMapMarkedAlt,
  faHubspot,
  faStar,
  faBars,
  faPlusCircle,
  faEdit,
  faTrashAlt,
  faAngleDoubleLeft,
  faChevronRight,
  faTimesCircle,
  faTimes,
  faArrowsAltV,
  faUsers,
  faUsers,
  faChartBar,
  faCoins,
  faCheckDouble,
  faBan,
  faBalanceScale,
  faBook,
  faAngleDown,
  faList,
  faDotCircle,
  faSignOutAlt,
  faStarOfLife,
  faArrowRight,
  faEllipsisV,
);

Vue.component('font-awesome-icon', FontAwesomeIcon);
