export default {
  category: {
    PAYMENT: 'payment',
    PAYMENT_RENEWAL_SUCCESS: 'Renewal Success',
    PAYMENT_RENEWAL_PENDING: 'Renewal Pending',
  },
  screen: {
    PAYMENT_METHODS: 'PaymentMethods',
    PAYMENT_SUCCESS: 'paymentSuccess',
    BANK_DETAILS: 'bankDetails',
    BANK_ACCOUNT_VERIFY: 'bankAccountVerify',
    ESIGN_STATUS: 'eSignStatus',
    PAYMENT_STATUS: 'paymentStatus',
    PAYMENT_STATUS_CARD_DETAILS: 'StatusCardDetails',
    RELEASE_SLOT_BOOKING: 'ReleaseSlotBooking',
    RELEASE_CONFIRMATION: 'Release Confirmation',
    ADDRESS_SELECTION: 'Address Selection',
    SUMMARY: 'Summary',
    CLOSE_LOAN_SUMMARY: 'closeLoanSummary',
    JEWELS_SELECTION: 'jewelsSelection',
    PART_RELEASE_SUMMARY: 'partReleaseSummary',
    VIEW_SELECTED_JEWELS: 'viewSelectedJewels',
    JEWELS_VALIDATION_POPUP: 'jewelsValidationPopUp',
    INTEREST_PAYMENT_SUMMARY: 'interestPaymentSummary',
    PART_PAYMENT_SUMMARY: 'partPaymentSummary',
    DASHBOARD: 'Dashboard',
    REPLEDGE_LOAN_SUMMARY: 'repledgeLoanSummary',
    LOAN_AMOUNT_SELECTION_MODAL: 'LoanAmountSelectionModal',
    ACK_OF_PLEDGE: 'ackComponent',
    STATUS_CARDS: 'statusCards',
    RENEWAL_SUMMARY_CARD: 'RenewalSummaryCard',
    VIDEO_PLAYER_MODAL: 'VideoPlayerModal',
    AADHAAR_VERIFICATION: 'Aadhaar Verification',
    PIN_CONFIRMATION: 'PIN Confirmation',
    SET_PIN: 'Set PIN',
    CLOSURE_DISCREPANCY_SCREEN: 'Closure Discrepancy Screen',
  },
  EVENT_NAME: 'EventName',
  EVENT_SOURCE: 'Source',
  CAPABILITY_REPLEDGE: 'repledge',
  CAPABILITY_INTEREST: 'interest',
  CAPABILITY_CLOSURE: 'close_loan',
  CAPABILITY_PART_PAYMENT: 'part_payment',
  CAPABILITY_HARD_RECOVERY: 'hard_recovery',
  RPK_ID: 'RPKID',
  ORDER_NUMBER: 'Order Number',
  LOAN_TYPE_DEFAULT: 'renewal_default',
  LOAN_TYPE_MORE: 'renewal_more',
  LOAN_TYPE_ENHANCEMENT: 'loan_enhancement',
  // ------- Payment Related -------
  PAYMENT_ACTION: 'Action',
  PAYMENT_RELATEDLOAN: 'Related Loan',
  PAYMENT_STATIC_KEY: 'Static Key',
  PAYMENT_REDIRECTEDTO: 'Redirected To',
  PAYMENT_OPTIONS_1_SELECTED: 'Payment Option 1 Selected',
  PAYMENT_OPTIONS_2_SELECTED: 'Payment Option 2 Selected',
  PAYMENT_RPK_ID: 'RPK ID',
  PAYMENT_ORDER_ID: 'Order ID',
  PAYMENT_ORDER_STATUS: 'Order Status',
  PAYMENT_CONTINUE_OTP_TROUBLE_CLICKED: 'Continue From OTP Trouble Clicked',
  PAYMENT_OFFLINE_OTP_SCREEN_CLICKED: 'Offline OTP Screen Clicked',
  PAYMENT_DOWNLOAD_PC_LENDER_CLICKED: 'Download PC Lender Clicked',
  PAYMENT_DOWNLOAD_PC_RUPEEK_CLICKED: 'Download PC Rupeek Clicked',
  PAYMENT_DOWNLOAD_SUMMARY_PC_CLICKED: 'Download Summary PC Clicked',
  PAYMENT_DOWNLOAD_LE_SUMMARY_PC_CLICKED: 'Download LE Summary PC Clicked',
  PAYMENT_VIA_OTP_REATTEMPT_CLICKED: 'Via OTP Reattempt Clicked',
  PAYMENT_VIA_ESIGN_REATTEMPT_CLICKED: 'Via Esign Reattempt Clicked',
  PAYMENT_LENDER_ESIGN_CLICKED: 'Lender Esign Clicked',
  PAYMENT_RUPEEK_ESIGN_CLICKED: 'Rupeek Esign Clicked',
  PAYMENT_SIGNING_METHOD: 'Signing Method',
  PAYMENT_LE_LOAN: 'LE Loan',
  PAYMENT_LE_BANK_VERIFICATION_STATUS: 'LE Bank Status',
  PAYMENT_LE_DIGITAL_VERIFICATION_SUCCESS: 'LE - Digital verification Success',
  PAYMENT_LE_DIGITAL_VERIFICATION_FAILED: 'LE - Digital verification Failed',
  PAYMENT_LE_LINK_VERIFICATION_FAILED_CLICKED:
    'LE - "link" in the verification failed final page Clicked',
  PAYMENT_BANK_VERIFICATION_LIST_PAGE: 'Bank Account Verification Page',
  PAYMENT_BANK_ADD_NEW_ACCOUNT_FLOATING_CLICKED: 'Add New Account Floating Button Clicked',
  PAYMENT_BANK_ADD_ACCOUNT_CLICKED: 'Add Account Button Clicked',
  PAYMENT_BANK_CONTINUE_CLICKED: 'Continue Button Clicked',
  PAYMENT_BANK_CHECKBOX_CLICKED: 'Transfer Consent Checkbox Clicked',
  PAYMENT_BANK_OTP_PAGE: 'Visited Bank OTP Page',
  PAYMENT_BANK_SUBMIT_OTP_PAGE_CLICKED: 'Submit in OTP Page Clicked',
  PAYMENT_BANK_VERIFICATION_FAILED_POPUP: 'Bank A/c verification failed popup',
  PAYMENT_BANK_VERIFICATION_FAILED_POPUP_RETRY_CLICKED:
    'Retry Clicked on Bank A/c verification failed popup',
  PAYMENT_RENEWAL_SUCCESS: 'Renewal Success',
  PAYMENT_RENEWAL_PENDING: 'Renewal Pending',
  PAYMENT_VISITED_STATUS_CARD_DETAILS: 'Release Status Card Details - Screen Visited',
  PAYMENT_CLICKED_ON_RELEASE_VIDEO: 'Release Status Card Details - Release Video Clicked',
  PAYMENT_VIEWED_OTP_DETAILS: 'Release Status Card Details - OTP Viewed',
  PAYMENT_VIEWED_GOLD_DELIVERY_SUCCESSFUL_STATUS: 'Release Status Card Details - Gold Delivered Screen Visited',
  PAYMENT_DATE: 'Date',
  PAYMENT_TIME: 'Time',
  PINCODE_SERVICEABLE: 'Pincode Serviceable',
  SLOTS_AVAILABLE: 'Slots Available',
  PAYMENT_ADD_ADDRESS_CLICKED: 'Add Address Clicked',
  PAYMENT_ADD_NEW_ADDRESS_CLICKED: 'Add New Address Clicked',
  PAYMENT_SELECTED_ADDRESS_MAPS: 'Address Selected from Maps',
  PAYMENT_SELECTED_DELIVERY_ADDRESS: 'Delivery Address Selected',
  PAYMENT_CONFIRM_ADDRESS_CLICKED: 'Confirm Address Clicked',
  PAYMENT_CHANGE_ADDRESS_CLICKED: 'Change Address Clicked',
  PAYMENT_VIEW_DETAILS_CLICKED: 'View Details Clicked',
  PAYMENT_DATE_SELECTED: 'Date Selected',
  PAYMENT_SLOT_SELECTED: 'Slot Selected',
  PAYMENT_CONFIRM_SLOT_CLICKED: 'Confirm Slot Clicked',
  PAYMENT_NO_SLOT_AVAILABLE_VISITED: 'No Slot Available Visited',
  PAYMENT_PROCEED_WITHOUT_SLOT_BOOKING: 'Proceed Without Slot Booking',
  PAYMENT_PINCODE_NOT_SEVICEABLE_VISITED: 'Pincode Not Seviceable Visited',
  PAYMENT_RELEASE_CONFIRMATION_SCREEN_VISITED: 'Release Confirmation Screen Visited',
  PAYMENT_TRACK_YOUR_GOLD_CLICKED: 'Track your Gold Clicked',
  PAYMENT_BOOK_GOLD_DELIVERY_SLOT_CLICKED: 'Book Gold Delivery Slot Clicked',
  PAYMENT_READ_MORE_CLICKED: 'Read More Clicked',
  PAYMENT_STATUS_CARD_PINCODE_NOT_SERVICEABLE: 'Status Card Pincode Not Serviceable',
  PAYMENT_STATUS_MESSAGE_VIEWED: 'Status Message Viewed',
  PAYMENT_CHANGE_SLOT_CLICKED: 'Change Slot Clicked',
  PAYMENT_DELIVERY_ADDRESS_SELECTED: 'Delivery Address Selected',
  PAYMENT_RESCHEDULE_SLOT_VISITED: 'Reschedule Slot Visited',
  PAYMENT_MULTIPLE_SLOT_BOOKING_VISITED: 'Multiple Slot Booking Visited',
  PAYMENT_QUESTION_MARK_ICON_CLICKED: 'Question Mark Icon Clicked',
  PAYMENT_FORMAT_DOCUMENT_CLICKED: 'Format Document Clicked',
  PAYMENT_CONTINUE_TO_PAY_SUMMARY_CLICKED: 'Continue To Pay Summary Clicked',
  PAYMENT_MORE_SUMMARY_CLICKED: 'More Summary Clicked',
  PAYMENT_SECURED_COMPONENT_DESELECTED: 'Secured Component Deselected',
  PAYMENT_PART_RELEASE_CLOSURE_SUMMARY_PAGE: 'Closure Summary Visited',
  PAYMENT_METHODS_PAY_CLICKED: 'Pay Button In Payment Options Page Clicked',
  PAYMENT_CORE_ID: 'Core ID',
  PAYMENT_AMOUNT: 'Amount',
  PAYMENT_LENDER_ID: 'Lender ID',
  PAYMENT_SUCCESSFUL: 'Payment Successful - v2',
  PAYMENT_UNSUCCESSFUL: 'Payment Unsuccessful',
  PAYMENT_TRY_AGAIN_CLICKED: 'Try Again Clicked',
  PAYMENT_ADD_TO_LOAN_CLOSURE_OPTION_CLICKED: 'Add to Loan Closure Clicked - Jewel Error PopUp',
  PAYMENT_JEWEL_SELECTION_CONTINUE_CLICKED: 'Continue From Jewel Selection',
  PAYMENT_PART_RELEASE_CLOSURE_POPUP_PART_RELEASE_OPTION_CLICKED: 'Part Release Clicked - Jewel Error PopUp',
  PAYMENT_PART_RELEASE_CLOSURE_POPUP_CLOSURE_OPTION_CLICKED: 'Closure Clicked - Jewel Error PopUp',
  PAYMENT_PART_RELEASE_SUMMARY_PAGE: 'Part Release Summary Visited',
  PAYMENT_PART_RELEASE_SUMMARY_PAGE_VIEW_SELECTED_JEWELS_CLICKED: 'Part Release View Selected Jewels Clicked',
  PAYMENT_PART_RELEASE_SUMMARY_PAGE_MODIFY_JEWELS_CLICKED: 'Part Release Modify Jewels Clicked',
  PAYMENT_PART_RELEASE_SUMMARY_PAGE_VIEW_SCHEME_DETAILS_CLICKED: 'Part Release View Scheme Details Clicked',
  PAYMENT_PART_RELEASE_SUMMARY_PAGE_ACCEPT_CONTINUE_CLICKED: 'Part Release Continue From Summary Clicked',
  PAYMENT_PART_RELEASE_PAYMENT_PAGE_PAY_CLICKED: 'Pay Button In Payment Options Page Clicked',
  PAYMENT_PART_RELEASE_SUCCESSFUL_PAGE: 'Part Release Successful',
  PAYMENT_JEWEL_SELECTION_SAME_LENDER_SAME_BRANCH_EXPAND_ARROW_CLICKED: 'Clicked on Expandable Jewel List Bar',
  PAYMENT_REPAYMENT_OPTION_DISABLED_CASE_I_ICON_CLICKED: 'i Icon on option disabled clicked',
  PAYMENT_ERROR_TAGS: 'errorTags',
  JEWEL_SELECTION_ERROR_POPUP: 'Jewel Selection Error PopUp',
  PAYMENT_LOAN_SELECTED: 'Loan Selected',
  PAYMENT_CORE_KEYWORD_MAPPING: 'Core - Keyword Map',
  PAYMENT_RELATED_LOAN: 'Related Loan',
  PAYMENT_REPAY_OTHER_LOANS_CLICKED: 'Repay Other Loans Clicked',
  PAYMENT_CONTINUE_TO_PAY_REPAY_LOAN_CLICKED: 'Continue To Pay Repay Loan Clicked',
  PAYMENT_RENEWAL_CONTINUE_FROM_SUMMARY_CLICKED: 'Renewal Continue From Summary Clicked',
  PAYMENT_INTEREST_RATE_CHANGE_POPUP: 'Interest Rate Change Popup',
  PAYMENT_INTEREST_RATE_CHANGE_PENDING_LOAN_POPUP: 'Interest Rate Change Pending Loan Popup',
  PAYMENT_INTEREST_RATE_FIRST_OPTION_SELECTED: 'Interest Rate First Option Selected',
  PAYMENT_INTEREST_RATE_SECOND_OPTION_SELECTED: 'Interest Rate Second Option Selected',
  PAYMENT_SELECT_SCHEME_CLICKED: 'Select Scheme Clicked',
  PAYMENT_RENEWAL_I_ICON_CLICKED: 'Renewal I Icon Clicked',
  PAYMENT_RENEWAL_READ_MORE_TC_LENDER_CLICKED: 'Renewal Read More T&C Lender Clicked',
  PAYMENT_RENEWAL_READ_MORE_TC_RUPEEK_CLICKED: 'Renewal Read More T&C Rupeek Clicked',
  PAYMENT_RENEWAL_DETAILS_LINK_CLICKED: 'Renewal Details Link Clicked',
  PAYMENT_RENEWAL_GET_TOP_UP_AMOUNT_CLICKED: 'Get Top Up Amount Clicked',
  PAYMENT_RENEWAL_HIGHER_AMOUNT_OPTION_SELECTED: 'Renewal Higher Amount Option Selected',
  PAYMENT_RENEWAL_LOWER_AMOUNT_OPTION_SELECTED: 'Renewal Lower Amount Option Selected',
  PAYMENT_LE_TOP_UP_OPTION_SELECTED: 'Top-Up Option Selected',
  PAYMENT_RENEWAL_CONFIRM_LOAN_AMOUNT_CLICKED: 'Confirm & Continue from New Loan Amount section Clicked',
  PAYMENT_NUMBER_OF_DELIVERIES: 'Number Of Deliveries',
  PAYMENT_RENEWAL_PARTIAL: 'Is Partial',
  PAYMENT_LOAN_TYPE: 'Loan Type',
  SIGNIN_VIA_OTP_CLICKED: 'Via OTP Clicked',
  SIGNING_VIA_OFFLINE_CLICKED: 'Via Offline Clicked',
  SIGNING_VIA_ESIGN_CLICKED: 'Via Esign Clicked',
  PAYMENT_VIA_OTP_STATUS_CLICKED: 'Via OTP Status Card Clicked',
  PAYMENT_VIA_ESIGN_STATUS_CLICKED: 'Via Esign Status Card Clicked',
  PAYMENT_STATUS_CARD_FROM_HOME_PAGE_CLICKED: 'Status Card From Home Page Clicked',
  PAYMENT_STATUS_CARD_FROM_REPAY_LOAN_CLICKED: 'Status Card From Repay Loan Clicked',
  PAYMENT_HARD_RECOVERY_FROM_HOME_PAGE_CLICKED: 'Hard Recovery From Home Page Clicked',
  PAYMENT_HARD_RECOVERY_FROM_REPAY_LOAN_CLICKED: 'Hard Recovery From Repay Loan Clicked',
  PAYMENT_ACKNOWLEDGE_PC_STATUS_CARD_CLICKED: 'Acknowledge PC From Status Card Clicked',
  PAYMENT_VERIFY_BANK_ACCOUNT_STATUS_CARD_CLICKED: 'Verify Bank Account from Status Card Clicked',
  PAYMENT_PART_RELEASE_STATUS_CARD_CLICK: 'Status Card Item Clicked',
  PAYMENT_GOLD_PRICE_ADJUSTMENT_INFO_CLICKED: 'Renewal Gold price info link clicked',
  PAYMENT_GOLD_PRICE_ADJUSTMENT_THUMBNAIL_CLICKED: 'Renewal Gold Price video link clicked',
  PAYMENT_GOLD_PRICE_ADJUSTMENT_VIDEO_CLOSED: 'Renewal Gold price video closed',
  PAYMENT_TOTAL_INTEREST_AMOUNT_INFO_CLICKED: 'Renewal Total Interest info clicked',
  CLICKED_ON_VIEW_MORE_FROM_STATUS_CARD: 'Home Status Card - View More Clicked',
  CLICKED_ON_YOU_HAVE_N_MORE_DELIVERIES_IN_PROGRESS_FROM_STATUS_CARD: 'Home Status Card - You Have N More Deliveries Clicked',
  CLICKED_ON_TRACK_YOUR_GOLD_ON_STATUS_CARD_LIST: 'Release Status Card - Track your Gold Clicked',
  PAYMENT_VALID_OVD_ENTERED: 'Valid OVD entered',
  PAYMENT_VALID_PIN_ENTERED: 'Valid PIN entered',
  PAYMENT_VALID_OTP_ENTERED: 'Valid OTP entered',
  PAYMENT_VIA_OTP_REATTEMPT_VIEWED: 'Via OTP Reattempt viewed',
  PAYMENT_CLICKED_ON_FORGOT_PIN: 'Clicked on forgot PIN',
  PAYMENT_INVALID_OVD_ENTERED: 'Invalid OVD entered',
  PAYMENT_INVALID_PIN_ENTERED: 'Invalid PIN entered',
  PAYMENT_INVALID_OTP_ENTERED: 'Invalid OTP entered',
  PAYMENT_PIN_SETUP_INITIATED: 'Pin Setup Initiated',
  PAYMENT_PIN_SETUP_SUCCESSFUL: 'Pin setup successful',
  CLOSURE_DISCREPANCY_POPUP_VISITED: 'Closure Discrepancy Popup Visited',
  CLOSE_LOAN_CLICKED_CLOSURE_DISCREPANCY: 'Close Loan Clicked - Closure Discrepancy Popup',
  GO_BACK_CLICKED_CLOSURE_DISCREPANCY: 'Go Back Clicked - Closure Discrepancy Popup',
};
