JSON_STRING='window.configs = { \
  "NODE_ENV":"'"${NODE_ENV}"'", \
  "VUE_APP_API_GATEWAY_URI":"'"${VUE_APP_API_GATEWAY_URI}"'", \
  "VUE_APP_PAYMENTS_URL":"'"${VUE_APP_PAYMENTS_URL}"'", \
  "VUE_APP_OMS_HOST":"'"${VUE_APP_OMS_HOST}"'", \
  "VUE_APP_PAY_HOST":"'"${VUE_APP_PAY_HOST}"'", \
  "VUE_APP_CIS_HOST":"'"${VUE_APP_CIS_HOST}"'", \
  "VUE_APP_RELEASE_HOST":"'"${VUE_APP_RELEASE_HOST}"'", \
  "VUE_APP_LOAN_HOST":"'"${VUE_APP_LOAN_HOST}"'", \
  "VUE_APP_REFERRAL_HOST":"'"${VUE_APP_REFERRAL_HOST}"'", \
  "VUE_APP_DOMAIN":"'"${VUE_APP_DOMAIN}"'", \
  "VUE_APP_CLEVERTAP_ID":"'"${VUE_APP_CLEVERTAP_ID}"'", \
  "VUE_APP_ACCOUNT_ID":"'"${VUE_APP_ACCOUNT_ID}"'", \
  "VUE_APP_AGENT_ID":"'"${VUE_APP_AGENT_ID}"'", \
  "VUE_APP_LICENSE_KEY":"'"${VUE_APP_LICENSE_KEY}"'",\
  "VUE_APP_LENDING_HOST":"'"${VUE_APP_LENDING_HOST}"'",\
  "VUE_APP_FIREBASE_API_KEY":"'"${VUE_APP_FIREBASE_API_KEY}"'", \
  "VUE_APP_FIREBASE_APP_ID":"'"${VUE_APP_FIREBASE_APP_ID}"'", \
  "VUE_APP_FIREBASE_AUTH_DOMAIN":"'"${VUE_APP_FIREBASE_AUTH_DOMAIN}"'", \
  "VUE_APP_FIREBASE_MEASUREMENT_ID":"'"${VUE_APP_FIREBASE_MEASUREMENT_ID}"'", \
  "VUE_APP_FIREBASE_MESSAGING_SENDER_ID":"'"${VUE_APP_FIREBASE_MESSAGING_SENDER_ID}"'", \
  "VUE_APP_FIREBASE_PROJECT_ID":"'"${VUE_APP_FIREBASE_PROJECT_ID}"'", \
  "VUE_APP_GMAPS_TOKEN":"'"${VUE_APP_GMAPS_TOKEN}"'",\
  "VUE_APP_BETA_URL":"'"${VUE_APP_BETA_URL}"'",\
  "VUE_APP_AAA_HOST":"'"${VUE_APP_AAA_HOST}"'",\
  "VUE_APP_FIREBASE_STORAGE_BUCKET":"'"${VUE_APP_FIREBASE_STORAGE_BUCKET}"'"\
}'
sed -i "s@// CONFIGURATIONS_PLACEHOLDER@${JSON_STRING}@" /usr/share/nginx/html/index.html
exec "$@"